import {
  Role,
  User,
  ModulePermissionConfig,
  PermissionMatrixState,
  ApprovalRule,
  AuditLogEntry,
  SystemSettingsState,
  RoleId,
} from './types';

export const ROLES_DATA: Role[] = [
  {
    id: 0,
    name: 'Super Admin',
    code: 'ROLE_0_SUPER_ADMIN',
    description: 'Full unrestricted system, database, and financial configuration control',
    colorName: 'violet',
    bgClass: 'bg-purple-50',
    textClass: 'text-purple-700',
    borderClass: 'border-purple-200',
    hexColor: '#7C3AED',
    isSystemProtected: true,
    userCount: 1,
    hierarchyLevel: 0,
  },
  {
    id: 1,
    name: 'Admin',
    code: 'ROLE_1_ADMIN',
    description: 'System configuration, user administration, elevated approvals, and audit viewing',
    colorName: 'rose',
    bgClass: 'bg-rose-50',
    textClass: 'text-rose-700',
    borderClass: 'border-rose-200',
    hexColor: '#BE123C',
    isSystemProtected: false,
    userCount: 1,
    hierarchyLevel: 1,
  },
  {
    id: 2,
    name: 'Manager',
    code: 'ROLE_2_MANAGER',
    description: 'Branch oversight, credit underwriting, loan approvals, and staff management',
    colorName: 'emerald',
    bgClass: 'bg-emerald-50',
    textClass: 'text-emerald-700',
    borderClass: 'border-emerald-200',
    hexColor: '#059669',
    isSystemProtected: false,
    userCount: 1,
    hierarchyLevel: 2,
  },
  {
    id: 3,
    name: 'Accountant',
    code: 'ROLE_3_ACCOUNTANT',
    description: 'General ledger, daily cash book, bank reconciliations, vouchers, and payouts',
    colorName: 'blue',
    bgClass: 'bg-blue-50',
    textClass: 'text-blue-700',
    borderClass: 'border-blue-200',
    hexColor: '#2563EB',
    isSystemProtected: false,
    userCount: 1,
    hierarchyLevel: 3,
  },
  {
    id: 4,
    name: 'Collection Agent',
    code: 'ROLE_4_COLLECTION_AGENT',
    description: 'Field collection routes, EMI receipts entry, customer visit status, and cash handover',
    colorName: 'amber',
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-800',
    borderClass: 'border-amber-200',
    hexColor: '#D97706',
    isSystemProtected: false,
    userCount: 3,
    hierarchyLevel: 4,
  },
  {
    id: 5,
    name: 'Employee',
    code: 'ROLE_5_EMPLOYEE',
    description: 'Standard internal personnel, attendance, internal leaves, and assigned tickets',
    colorName: 'slate',
    bgClass: 'bg-slate-100',
    textClass: 'text-slate-700',
    borderClass: 'border-slate-300',
    hexColor: '#64748B',
    isSystemProtected: false,
    userCount: 0,
    hierarchyLevel: 5,
  },
  {
    id: 6,
    name: 'Customer',
    code: 'ROLE_6_CUSTOMER',
    description: 'Borrower portal view: active loans, repayment schedule, dues, and payment slips',
    colorName: 'ink',
    bgClass: 'bg-slate-900',
    textClass: 'text-slate-100',
    borderClass: 'border-slate-800',
    hexColor: '#0F172A',
    isSystemProtected: false,
    userCount: 42,
    hierarchyLevel: 6,
  },
];

export const MODULES_DATA: ModulePermissionConfig[] = [
  {
    id: 'dashboard',
    name: 'Financial Dashboard',
    category: 'Core',
    description: 'High-level financial KPIs, portfolio charts, and executive metrics',
    actions: ['view', 'export'],
  },
  {
    id: 'loans',
    name: 'Loan Management',
    category: 'Finance',
    description: 'Disbursements, interest calculation, rescheduling, and foreclosure',
    actions: ['view', 'create', 'edit', 'delete', 'approve', 'export'],
  },
  {
    id: 'customers',
    name: 'Customer Directory',
    category: 'Operations',
    description: 'KYC records, guarantor profiles, credit scores, and customer ledger',
    actions: ['view', 'create', 'edit', 'delete', 'export'],
  },
  {
    id: 'income',
    name: 'Income & Revenue',
    category: 'Finance',
    description: 'Interest earnings, penalty fees, documentation charges, and other income',
    actions: ['view', 'create', 'edit', 'delete', 'export'],
  },
  {
    id: 'expenses',
    name: 'Expense Tracking',
    category: 'Finance',
    description: 'Operational expenses, rent, utilities, office tea, and vendor bills',
    actions: ['view', 'create', 'edit', 'delete', 'approve', 'export'],
  },
  {
    id: 'collections',
    name: 'Collections & Recovery',
    category: 'Operations',
    description: 'Daily collection logs, route management, OD followups, and receipts',
    actions: ['view', 'create', 'edit', 'delete', 'approve', 'export'],
  },
  {
    id: 'salary',
    name: 'Salary & Payroll',
    category: 'Finance',
    description: 'Staff payroll, attendance deductions, incentives, and salary slips',
    actions: ['view', 'create', 'edit', 'delete', 'approve', 'export'],
  },
  {
    id: 'agents',
    name: 'Agent Network',
    category: 'Operations',
    description: 'Collection agent tracking, route allocation, and performance metrics',
    actions: ['view', 'create', 'edit', 'delete', 'export'],
  },
  {
    id: 'reports',
    name: 'Financial Reports',
    category: 'Finance',
    description: 'P&L statements, balance sheet, trial balance, and NPA aging analysis',
    actions: ['view', 'export'],
  },
  {
    id: 'accounting',
    name: 'Accounting & Ledger',
    category: 'Finance',
    description: 'Double-entry journals, chart of accounts, and daybook adjustments',
    actions: ['view', 'create', 'edit', 'delete', 'approve', 'export'],
  },
  {
    id: 'schedule',
    name: 'EMI Schedules',
    category: 'Operations',
    description: 'Repayment calendar, holiday adjustment, and collection planner',
    actions: ['view', 'edit', 'export'],
  },
  {
    id: 'requests',
    name: 'Requests & Approvals',
    category: 'Core',
    description: 'Multi-level workflow approvals, rate discounts, and threshold overrides',
    actions: ['view', 'create', 'approve', 'export'],
  },
  {
    id: 'admin',
    name: 'Administration',
    category: 'System',
    description: 'User access controls, directory management, audit trails, and global system config',
    actions: ['view', 'create', 'edit', 'delete', 'approve', 'export'],
  },
];

export const INITIAL_PERMISSION_MATRIX: PermissionMatrixState = {
  dashboard: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: true, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  loans: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: true },
    create: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    approve: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  customers: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: true, 6: true },
    create: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  income: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    create: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: false, 3: true, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  expenses: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    create: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: true, 6: false },
    edit: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    approve: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  collections: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: false },
    create: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    approve: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: false },
  },
  salary: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    create: { 0: true, 1: true, 2: false, 3: true, 4: false, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: false, 3: true, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: false },
    approve: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  agents: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    create: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
  },
  reports: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  accounting: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
    create: { 0: true, 1: true, 2: false, 3: true, 4: false, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: false, 3: true, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: false },
    approve: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  schedule: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: true },
    edit: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: false, 6: false },
  },
  requests: {
    view: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: true, 6: false },
    create: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: true, 6: false },
    approve: { 0: true, 1: true, 2: true, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: true, 3: true, 4: false, 5: false, 6: false },
  },
  admin: {
    view: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    create: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    edit: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    delete: { 0: true, 1: false, 2: false, 3: false, 4: false, 5: false, 6: false },
    approve: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
    export: { 0: true, 1: true, 2: false, 3: false, 4: false, 5: false, 6: false },
  },
};

const createSessions = (name: string): any[] => [
  {
    id: 'SESS-1',
    device: 'MacBook Pro 16" (Sonoma)',
    browser: 'Chrome 127.0.6533',
    ipAddress: '49.207.214.18',
    location: 'Chennai, Tamil Nadu, IN',
    lastActive: 'Active now',
    isCurrent: true,
  },
  {
    id: 'SESS-2',
    device: 'iPhone 15 Pro (iOS 17.5)',
    browser: 'Safari Mobile 17.4',
    ipAddress: '157.44.132.89',
    location: 'Coimbatore, Tamil Nadu, IN',
    lastActive: '2 hours ago',
    isCurrent: false,
  },
];

export const INITIAL_USERS: User[] = [
  // 1. Super Admin (Logs in with Email)
  {
    id: 'ADM-1001',
    name: 'System Administrator',
    email: 'admin@asrgroups.in',
    phone: '+91 98401 22345',
    loginMethod: 'email',
    initials: 'SA',
    assignedRoleIds: [0],
    primaryRoleId: 0,
    status: 'Active',
    department: 'Administration',
    designation: 'Super Administrator',
    joinedDate: '2021-03-01',
    createdAt: '2021-03-01 09:00',
    lastLogin: '2026-08-23 10:00',
    address: 'No. 42, ASR Towers, Mount Road, Chennai, TN - 600032',
    emergencyContact: '+91 98401 99887',
    twoFactorEnabled: true,
    sessions: createSessions('System Administrator'),
    isCustomer: false,
  },
  // 2. Admin (Logs in with Email)
  {
    id: 'USR-1002',
    name: 'Arun Venkat',
    email: 'arun.venkat@asrgroups.in',
    phone: '+91 97908 55432',
    loginMethod: 'email',
    initials: 'AV',
    assignedRoleIds: [1],
    primaryRoleId: 1,
    status: 'Active',
    department: 'Operations & IT',
    designation: 'Chief Technology Officer',
    joinedDate: '2022-06-15',
    createdAt: '2022-06-15 10:30',
    lastLogin: '2026-08-07 08:50',
    address: 'B-404, Olympia Opaline, Navalur, OMR, Chennai - 600130',
    emergencyContact: '+91 97908 11223 (Brother)',
    twoFactorEnabled: true,
    sessions: createSessions('Arun Venkat'),
    isCustomer: false,
  },
  // 3. Manager (Logs in with Username & Password)
  {
    id: 'USR-1003',
    name: 'Meera Suresh',
    username: 'meera.suresh',
    email: 'meera.suresh@asrgroups.in',
    phone: '+91 94440 88765',
    loginMethod: 'username',
    tempPassword: 'ASR@Manager2026',
    initials: 'MS',
    assignedRoleIds: [2],
    primaryRoleId: 2,
    status: 'Active',
    department: 'Credit Underwriting',
    designation: 'Senior Credit Manager',
    joinedDate: '2023-01-10',
    createdAt: '2023-01-10 11:00',
    lastLogin: '2026-08-06 10:05',
    address: '88, 4th Main Road, Gandhi Nagar, Adyar, Chennai - 600020',
    emergencyContact: '+91 94440 33445 (Spouse)',
    twoFactorEnabled: true,
    sessions: createSessions('Meera Suresh'),
    isCustomer: false,
  },
  // 4. Accountant (Logs in with Username & Password)
  {
    id: 'USR-1004',
    name: 'Rajesh Kumar',
    username: 'rajesh.kumar',
    email: 'rajesh.kumar@asrgroups.in',
    phone: '+91 98840 12345',
    loginMethod: 'username',
    tempPassword: 'ASR@Accounts2026',
    initials: 'RK',
    assignedRoleIds: [3],
    primaryRoleId: 3,
    status: 'Active',
    department: 'Accounts & Finance',
    designation: 'Head of Accounts',
    joinedDate: '2023-04-01',
    createdAt: '2023-04-01 09:30',
    lastLogin: '2026-08-07 07:45',
    address: '12, West Mada Street, Mylapore, Chennai - 600004',
    emergencyContact: '+91 98840 99001 (Father)',
    twoFactorEnabled: true,
    sessions: createSessions('Rajesh Kumar'),
    isCustomer: false,
  },
  // 5. Collection Agent 1 (Logs in with Username & Password)
  {
    id: 'USR-1005',
    name: 'Priya Sharma',
    username: 'priya.sharma',
    email: 'priya.sharma@asrgroups.in',
    phone: '+91 97100 44556',
    loginMethod: 'username',
    tempPassword: 'ASR@Agent2026',
    initials: 'PS',
    assignedRoleIds: [4],
    primaryRoleId: 4,
    status: 'Active',
    department: 'Recovery & Field Operations',
    designation: 'Senior Field Collection Lead',
    joinedDate: '2023-08-15',
    createdAt: '2023-08-15 10:00',
    lastLogin: '2026-08-07 09:00',
    address: '23, 2nd Avenue, Ashok Nagar, Chennai - 600083',
    emergencyContact: '+91 97100 66778 (Mother)',
    twoFactorEnabled: false,
    sessions: createSessions('Priya Sharma'),
    isCustomer: false,
  },
  // 6. Collection Agent 2 (Logs in with Username & Password)
  {
    id: 'USR-1006',
    name: 'Anand Verma',
    username: 'anand.verma',
    email: 'anand.verma@asrgroups.in',
    phone: '+91 98410 77889',
    loginMethod: 'username',
    tempPassword: 'ASR@Agent2026',
    initials: 'AV',
    assignedRoleIds: [4],
    primaryRoleId: 4,
    status: 'Active',
    department: 'Recovery & Field Operations',
    designation: 'Field Collection Officer (Central)',
    joinedDate: '2023-11-01',
    createdAt: '2023-11-01 09:15',
    lastLogin: '2026-08-06 18:30',
    address: '45, Lake View Road, West Mambalam, Chennai - 600033',
    emergencyContact: '+91 98410 22334 (Brother)',
    twoFactorEnabled: false,
    sessions: createSessions('Anand Verma'),
    isCustomer: false,
  },
  // 7. Collection Agent 3 (Logs in with Username & Password)
  {
    id: 'USR-1007',
    name: 'Vasanth R',
    username: 'vasanth.r',
    email: 'vasanth.r@asrgroups.in',
    phone: '+91 99400 33221',
    loginMethod: 'username',
    tempPassword: 'ASR@Agent2026',
    initials: 'VR',
    assignedRoleIds: [4],
    primaryRoleId: 4,
    status: 'Active',
    department: 'Recovery & Field Operations',
    designation: 'Field Collection Officer (South)',
    joinedDate: '2024-02-10',
    createdAt: '2024-02-10 10:45',
    lastLogin: '2026-08-07 08:15',
    address: '56, Medavakkam Main Road, Madipakkam, Chennai - 600091',
    emergencyContact: '+91 99400 88990 (Father)',
    twoFactorEnabled: false,
    sessions: createSessions('Vasanth R'),
    isCustomer: false,
  },
];

// Generate remaining 41 customers to achieve: Total 48, Active 45, Suspended 2, Pending 1.
const customerNames = [
  'Fathima Noor',
  'Suresh Kannan',
  'Divya Bharathi',
  'Karthik Sundaram',
  'Vignesh Murugan',
  'Lakshmi Narayanan',
  'Balaji Parthasarathy',
  'Deepa Sridhar',
  'Manikandan Natarajan',
  'Revathi Sankar',
  'Selvam Mariappan',
  'Aarthi Gunasekaran',
  'Gopalakrishnan Iyer',
  'Radha Krishnan',
  'Murugesan Thangavel',
  'Saranya Venkatesh',
  'Ramesh Babu',
  'Kavitha Ramesh',
  'Mohan Raj',
  'Janani Sundaresan',
  'Babu Chandran',
  'Shanthi Palani',
  'Vijay Anand',
  'Anitha Selvaraj',
  'Manoj Kumar',
  'Pavithra Sekar',
  'Naveen Prasad',
  'Suganya Mani',
  'Harish Raghavan',
  'Geetha Govind',
  'Sundar Rajan',
  'Keerthana Mohan',
  'Gautham Viswanathan',
  'Swetha Ramachandran',
  'Praveen Kumar',
  'Nithya Senthil',
  'Saravanan Muthu',
  'Bhuvaneswari K',
  // Suspended 1:
  'Dinesh Kumar',
  // Suspended 2:
  'Prakash R',
  // Pending 1:
  'Sangeetha M',
];

customerNames.forEach((name, idx) => {
  const userIdNum = 1008 + idx;
  const isSuspended = name === 'Dinesh Kumar' || name === 'Prakash R';
  const isPending = name === 'Sangeetha M';
  const status = isSuspended ? 'Suspended' : isPending ? 'Pending' : 'Active';
  const names = name.split(' ');
  const initials = names.map((n) => n[0]).join('').slice(0, 2);
  const emailName = name.toLowerCase().replace(/[^a-z]/g, '.');

  INITIAL_USERS.push({
    id: `USR-${userIdNum}`,
    name,
    username: emailName,
    email: `${emailName}@gmail.com`,
    phone: `+91 ${98000 + idx} ${10000 + idx * 77}`,
    loginMethod: 'username',
    tempPassword: 'ASR@Cust2026',
    initials,
    assignedRoleIds: [6],
    primaryRoleId: 6,
    status,
    department: 'Retail Borrowers',
    designation: 'Loan Borrower',
    joinedDate: '2024-03-01',
    createdAt: '2024-03-01 11:30',
    lastLogin: isSuspended ? '2026-07-15 14:20' : '2026-08-06 16:45',
    address: `${idx + 10}, Trunk Road, Porur, Chennai - 600116`,
    emergencyContact: `+91 97000 ${20000 + idx * 33}`,
    twoFactorEnabled: false,
    suspendReason: isSuspended ? 'Account locked due to 3 continuous default notices' : undefined,
    sessions: createSessions(name),
    isCustomer: true,
  });
});

export const INITIAL_APPROVAL_RULES: ApprovalRule[] = [
  {
    id: 'RULE-101',
    changeType: 'Loan Update',
    description: 'Modifications to disbursed loan principal, interest rate discount, or tenure extension',
    whoCanRaise: [2, 3], // Manager, Accountant
    whoMustApprove: 1, // Admin or Super Admin
    amountThreshold: 50000,
    autoApproveBelow: true,
    isActive: true,
    createdAt: '2024-01-10 10:00',
    updatedAt: '2026-07-20 14:30',
  },
  {
    id: 'RULE-102',
    changeType: 'Collection Correction',
    description: 'Manual adjustment or cancellation of recorded cash collection receipt by field agent',
    whoCanRaise: [4], // Collection Agent
    whoMustApprove: 2, // Manager
    amountThreshold: 5000,
    autoApproveBelow: false,
    isActive: true,
    createdAt: '2024-01-15 11:30',
    updatedAt: '2026-08-01 09:15',
  },
  {
    id: 'RULE-103',
    changeType: 'Expense Edit',
    description: 'Post-approval modification or retrospective booking of branch operational expenses',
    whoCanRaise: [2, 3, 5], // Manager, Accountant, Employee
    whoMustApprove: 2, // Manager
    amountThreshold: 10000,
    autoApproveBelow: true,
    isActive: true,
    createdAt: '2024-02-01 14:00',
    updatedAt: '2026-07-28 16:20',
  },
  {
    id: 'RULE-104',
    changeType: 'Salary Change',
    description: 'Revision of staff base pay, incentive bracket update, or special allowance grant',
    whoCanRaise: [3], // Accountant
    whoMustApprove: 0, // Super Admin only
    amountThreshold: 0,
    autoApproveBelow: false,
    isActive: true,
    createdAt: '2024-02-15 16:45',
    updatedAt: '2026-08-02 11:00',
  },
  {
    id: 'RULE-105',
    changeType: 'Customer Update',
    description: 'Alteration of primary Aadhaar KYC, bank disbursement account, or guarantor details',
    whoCanRaise: [2, 4], // Manager, Collection Agent
    whoMustApprove: 2, // Manager
    amountThreshold: 0,
    autoApproveBelow: false,
    isActive: true,
    createdAt: '2024-03-01 09:00',
    updatedAt: '2026-08-05 13:10',
  },
  {
    id: 'RULE-106',
    changeType: 'Role Change',
    description: 'Granting elevated role access (Admin/Manager) or enabling multiple roles for any staff',
    whoCanRaise: [1], // Admin
    whoMustApprove: 0, // Super Admin only
    amountThreshold: 0,
    autoApproveBelow: false,
    isActive: true,
    createdAt: '2024-01-05 08:30',
    updatedAt: '2026-08-07 09:14',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  // 4 canonical overview entries:
  {
    id: 'AUD-9404',
    timestamp: '2026-08-07 09:14',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Assigned Role',
    target: 'Arun Venkat (USR-1002)',
    beforeVal: 'Role: [Manager]',
    afterVal: 'Role: [Admin (1)]',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: true,
  },
  {
    id: 'AUD-9403',
    timestamp: '2026-08-07 08:50',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Approved Request',
    target: 'Request RQ-5009 (Disbursement)',
    beforeVal: 'Status: Pending Review',
    afterVal: 'Status: Approved (₹3,50,000)',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: false,
  },
  {
    id: 'AUD-9402',
    timestamp: '2026-08-06 17:22',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Edited Permission',
    target: 'Manager Role (Role 2) - Expense Edit',
    beforeVal: 'Expense Edit: DENIED',
    afterVal: 'Expense Edit: ALLOWED',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: true,
  },
  {
    id: 'AUD-9401',
    timestamp: '2026-08-06 10:05',
    actorId: 'USR-1003',
    actorName: 'Meera Suresh',
    actorRoleId: 2,
    action: 'Login',
    target: 'Session Authenticated (2FA Verified)',
    beforeVal: '-',
    afterVal: 'IP: 182.73.24.110',
    ipAddress: '182.73.24.110',
    device: 'macOS / Safari',
    isSensitive: false,
  },
  // Additional realistic audit events spanning the last 30 days:
  {
    id: 'AUD-9400',
    timestamp: '2026-08-06 09:30',
    actorId: 'USR-1004',
    actorName: 'Rajesh Kumar',
    actorRoleId: 3,
    action: 'Login',
    target: 'Daily Daybook Reconciliation session',
    beforeVal: '-',
    afterVal: 'Success',
    ipAddress: '49.207.199.45',
    device: 'Windows 11 / Chrome',
    isSensitive: false,
  },
  {
    id: 'AUD-9399',
    timestamp: '2026-08-05 16:40',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Modified Shareholder Split',
    target: 'Shareholder Split Config',
    beforeVal: 'Sunrise 45%, Vaanavil 35%, RK 20%',
    afterVal: 'Sunrise 40%, Vaanavil 35%, RK 25%',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: true,
  },
  {
    id: 'AUD-9398',
    timestamp: '2026-08-05 14:15',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Suspended User',
    target: 'Dinesh Kumar (USR-1046)',
    beforeVal: 'Status: Active',
    afterVal: 'Status: Suspended (Default Notice)',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: true,
  },
  {
    id: 'AUD-9397',
    timestamp: '2026-08-04 18:20',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Suspended User',
    target: 'Prakash R (USR-1047)',
    beforeVal: 'Status: Active',
    afterVal: 'Status: Suspended (Overdue 90d)',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: true,
  },
  {
    id: 'AUD-9396',
    timestamp: '2026-08-04 11:10',
    actorId: 'USR-1003',
    actorName: 'Meera Suresh',
    actorRoleId: 2,
    action: 'Approved Request',
    target: 'Loan Application LN-8921 (Priya Stores)',
    beforeVal: 'Pending Underwriting',
    afterVal: 'Approved (₹5,00,000 @ 18% ROI)',
    ipAddress: '182.73.24.110',
    device: 'macOS / Safari',
    isSensitive: false,
  },
  {
    id: 'AUD-9395',
    timestamp: '2026-08-03 15:45',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Triggered Backup',
    target: 'Cloud Database Snapshot (PostgreSQL DB-PROD-01)',
    beforeVal: 'Snapshot Size: 1.42 GB',
    afterVal: 'Completed successfully (1.44 GB)',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: false,
  },
  {
    id: 'AUD-9394',
    timestamp: '2026-08-02 12:00',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Created User',
    target: 'Vasanth R (USR-1007)',
    beforeVal: 'New Record',
    afterVal: 'Assigned: Collection Agent (4)',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: false,
  },
  {
    id: 'AUD-9393',
    timestamp: '2026-08-01 10:30',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Updated Approval Rule',
    target: 'RULE-101 (Loan Update Threshold)',
    beforeVal: 'Threshold: ₹25,000',
    afterVal: 'Threshold: ₹50,000',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: true,
  },
  {
    id: 'AUD-9392',
    timestamp: '2026-07-31 17:15',
    actorId: 'USR-1004',
    actorName: 'Rajesh Kumar',
    actorRoleId: 3,
    action: 'Approved Request',
    target: 'Monthly Salary Batch - July 2026',
    beforeVal: 'Draft (₹18.45 L)',
    afterVal: 'Disbursed (₹18.45 L)',
    ipAddress: '49.207.199.45',
    device: 'Windows 11 / Chrome',
    isSensitive: false,
  },
  {
    id: 'AUD-9391',
    timestamp: '2026-07-30 09:40',
    actorId: 'USR-1005',
    actorName: 'Priya Sharma',
    actorRoleId: 4,
    action: 'Login',
    target: 'Field Mobile Handset session',
    beforeVal: '-',
    afterVal: 'Android 14 / Chrome Mobile',
    ipAddress: '106.198.88.23',
    device: 'Samsung Galaxy A54',
    isSensitive: false,
  },
  {
    id: 'AUD-9390',
    timestamp: '2026-07-29 14:00',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Updated Settings',
    target: 'Security Policy - Session Timeout',
    beforeVal: 'Timeout: 60 minutes',
    afterVal: 'Timeout: 30 minutes',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: true,
  },
  {
    id: 'AUD-9389',
    timestamp: '2026-07-28 11:20',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Edited Permission',
    target: 'Accountant Role (Role 3) - Ledger Vouchers',
    beforeVal: 'Delete: DENIED',
    afterVal: 'Delete: DENIED (Retained lock)',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: true,
  },
  {
    id: 'AUD-9388',
    timestamp: '2026-07-27 16:50',
    actorId: 'USR-1003',
    actorName: 'Meera Suresh',
    actorRoleId: 2,
    action: 'Approved Request',
    target: 'Collateral Release - LN-7640',
    beforeVal: 'Pledged Gold Box #44',
    afterVal: 'Released to Customer',
    ipAddress: '182.73.24.110',
    device: 'macOS / Safari',
    isSensitive: false,
  },
  {
    id: 'AUD-9387',
    timestamp: '2026-07-26 10:10',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Reset Password',
    target: 'Anand Verma (USR-1006)',
    beforeVal: 'Manual Request via Helpdesk',
    afterVal: 'Temporary Credential Dispatched via SMS',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: true,
  },
  {
    id: 'AUD-9386',
    timestamp: '2026-07-25 15:30',
    actorId: 'USR-1001',
    actorName: 'Karthik Rajan',
    actorRoleId: 0,
    action: 'Triggered Backup',
    target: 'Weekly Scheduled Offsite Cold Archive',
    beforeVal: 'Archive ID: #WK-30',
    afterVal: 'AWS S3 Glacier Sync Success',
    ipAddress: '49.207.214.18',
    device: 'MacBook Pro / Chrome',
    isSensitive: false,
  },
  {
    id: 'AUD-9385',
    timestamp: '2026-07-24 13:45',
    actorId: 'USR-1002',
    actorName: 'Arun Venkat',
    actorRoleId: 1,
    action: 'Created User',
    target: 'Sangeetha M (USR-1048)',
    beforeVal: 'New Applicant',
    afterVal: 'Assigned: Customer (Pending KYC Approval)',
    ipAddress: '157.44.132.89',
    device: 'Windows 11 / Edge',
    isSensitive: false,
  },
];

export const INITIAL_SYSTEM_SETTINGS: SystemSettingsState = {
  companyProfile: {
    companyName: 'ASR Groups Finance ERP',
    legalEntityName: 'ASR Family Microfinance & Investment Private Limited',
    logoUrl: '/Groups Finalized.png',
    gstin: '33AABCA1234F1Z8',
    cin: 'U65929TN2018PTC123456',
    pan: 'AABCA1234F',
    registeredAddress: 'No. 42, ASR Towers, Mount Road, Guindy, Chennai, Tamil Nadu, 600032',
    baseCurrency: 'INR (₹)',
    currencySymbol: '₹',
    financialYearStart: '01-April',
    supportEmail: 'admin@asrgroups.in',
    supportPhone: '+91 44 2834 9900',
  },
  shareholders: [
    {
      id: 'SH-1',
      name: 'Sunrise Finance Pvt Ltd',
      registrationNumber: 'CIN-U65191TN2014PTC099881',
      percentage: 40,
      contactPerson: 'Karthik Rajan',
      email: 'investor.relations@sunrisefinance.in',
      phone: '+91 98401 22345',
      isPrimary: true,
    },
    {
      id: 'SH-2',
      name: 'Vaanavil Capital Holdings',
      registrationNumber: 'CIN-U67120TN2016PTC104523',
      percentage: 35,
      contactPerson: 'Venkatesh S',
      email: 'funds@vaanavilcapital.com',
      phone: '+91 98840 77112',
      isPrimary: false,
    },
    {
      id: 'SH-3',
      name: 'RK Holdings & Investments',
      registrationNumber: 'CIN-U65999TN2019PTC118944',
      percentage: 25,
      contactPerson: 'Radha Krishnan',
      email: 'partners@rkholdings.co.in',
      phone: '+91 94440 33991',
      isPrimary: false,
    },
  ],
  securityPolicy: {
    minPasswordLength: 10,
    requireSpecialChar: true,
    requireNumber: true,
    requireUppercase: true,
    sessionTimeoutMinutes: 30,
    enforce2FA: true,
    ipAllowlist: [
      '49.207.214.0/24 (Head Office Chennai)',
      '182.73.24.0/24 (Adyar Branch)',
      '157.44.132.0/24 (OMR Operations)',
    ],
    maxLoginAttempts: 5,
  },
  featureToggles: {
    customerSelfServicePortal: true,
    smsNotifications: false, // Greyed out/disabled as app is in-app notifications only
    autoApproveSmallExpenses: true,
    twoFactorEnforcement: true,
    darkModePreview: false,
    multiBranchSupport: true,
    strictIpWhitelist: false,
  },
  lastBackupTimestamp: '2026-08-07 03:00 AM',
  backupStatus: 'Completed',
};
